site_name: Pinax Documentation

pages:
  - index.md
  - Introduction:
    - 'What is Pinax?': what_is_pinax.md
    - Quick Start: quick_start.md
    - Quick Start Manual: quick_start_manual.md
    - History: history.md
    - FAQs: faq.md
  - Starter Projects:
    - Pinax Starter Projects: pinax_starter_projects.md
    - List of Starter Projects: starter_project_list.md
    - Pinax Theme Bootstrap: pinax_theme_bootstrap.md
  - Apps:
    - List of Apps: apps_list.md
  - How Tos:
    - LDAP Integration: how-tos/ldap.md
    - Deploying to Heroku: how-tos/deploy-to-heroku.md
    - Releasing a Starter Project: how-tos/release-starter-project.md
  - Development:
    - How to Contribute: how_to_contribute.md
    - Ways to Contribute: ways_to_contribute.md
    - Release Process: release_process.md
    - Code of Conduct: code_of_conduct.md
  - Tutorials:
    - Tutorials: tutorials.md
  - In the Wild:
    - In the Wild: in_the_wild.md
  - Companies Working with Pinax:
    - Companies Working with Pinax: companies_working_with_pinax.md

theme: readthedocs
